server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_db?useSSL=false&serverTimezone=UTC
    username: adeng
    password: adeng1024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
          max-file-size: 2MB
          max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 开启驼峰转换

file:
  upload-dir: /var/data/uploads

